### ISSUE TITLE
Basic equlaity and inequality test is failing on 0.5.6 release

### ISSUE THREAD

**Issue by rameshrajagopal** [lemire/EWAHBoolArray#14]
The below one is giving me wrong result. 

template <class uword> bool testInEqualityEWAHBoolArray() {
  cout << "[testing testInEqualityEWAHBoolArray] sizeof(uword)=" << sizeof(uword) << endl;
  EWAHBoolArray<uword> b1;
  EWAHBoolArray<uword> b = EWAHBoolArray<uword>::bitmapOf(3, 1, 10, 11);

  return !(b1 == b);
}     
I am expecting this should return true, where as this returns false.

**Comment by lemire** [comment]
Thanks. Fixed in release 0.5.7.
