### ISSUE TITLE
Space optimization for sparse bitmaps

### ISSUE THREAD

**Issue by bbala-github** [lemire/EWAHBoolArray#15]
Hi,
If EWAH bitmap has only a single bit set, it still consumes around a minimum of 20 bytes. In cases like these would it make sense to store the bit position as 4 byte integer and handle the bitmap creation and processing at runtime?
I am looking at options to reduce storage space as majority of our bitmaps and really sparse, at the expense of a minimal runtime overhead.
Are there other bitmap implementations that support this optimization.

**Comment by lemire** [comment]
Yes, try ``CRoaring`` (you can use the C++ wrapper). The non-portable serialization has an optimization for the sparse case:

https://github.com/RoaringBitmap/CRoaring/blob/master/cpp/roaring.hh#L219-L233

This could be implemented on top of ``EWAHBoolArray`` as well.

Closing as I think I have answered your request.

Reopen if you disagree.
