### ISSUE TITLE
Question about double indexing

### ISSUE THREAD

**Issue by gevago01** [lemire/EWAHBoolArray#20]
Thank you for contributing this amazing library!

I am sorry for posting a question as an issue.

My question is, can you index doubles using a compressed bitmap? 

In my understanding, I would need some kind of binning: If I have an attribute X ranging from [0-1] and 10 bins, then I would need 10 bitmaps, one for each range of values: i.e. 1 for [0-0.1], 1 for [0.1-0.2], etc. But then how do you do range queries on X?     

Have you got test code for this case?

**Comment by lemire** [comment]
I'm not sure I understand your question. We have a set of integers. There is no support for floating point numbers, none that make sense to me at least.

**Comment by gevago01** [comment]
My question is whether I can index floats using this library, like [Fastbit](http://graphics.idav.ucdavis.edu/~hamann/WuAhernBethelChenChildsGeddesHagenHamannRuebelShoshaniWeberEtAl2009SciDACPaperAsSubmitted05292009.pdf) can. Feel free to close the issue If I don't understand things right

**Comment by lemire** [comment]
@gevago01 

Well, yes, you can bin your values and be able to tell whether there is a value in the bin by marking it using a bit in the (compressed) bitmap.

Fastbit is a database engine, whereas EWAHBoolArray is a library that provides just the compressed bitmap. The idea behind EWAHBoolArray is that you can use the library to write your own database engine (like fastbit).

This means that you will need to write your code to do the binning.

You might enjoy this as well : http://roaringbitmap.org/

**Comment by gevago01** [comment]
Thank you Daniel! You've made things clear for me.

Thank you for the link. Roaring bitmaps seem even better! I will look into them

Giannis
