### ISSUE TITLE
sizeInBits() values are different for same bitmap.

### ISSUE THREAD

**Issue by imback82** [lemire/EWAHBoolArray#22]
I created a bitmap in two different ways but with the same bits set. However, the result bitmap behaves differently. Is this expected?

    {    // Create a bitmap with (1,2,3,4) using logicalors.
        auto ewah1 = EWAHBoolArray<>::bitmapOf(1, 1);
        auto ewah2 = EWAHBoolArray<>::bitmapOf(1, 2);
        auto ewah3 = EWAHBoolArray<>::bitmapOf(1, 3);
        auto ewah4 = EWAHBoolArray<>::bitmapOf(1, 4);
        auto result = ewah1 | ewah2 | ewah3 | ewah4;
        std::cout << result.set(5) << std::endl; // false b/c sizeInBits() == 32.
    }
    {    // Create a bitmap with (1, 2, 3, 4) in a naive way.
        auto result = EWAHBoolArray<>::bitmapOf(4, 1, 2, 3, 4);
        std::cout << result.set(5) << std::endl; // true b/c sizeInBits() == 5.
    }

**Comment by lemire** [comment]
Fixed in latest release.
