### ISSUE TITLE
read()/write() with raw buffer

### ISSUE THREAD

**Issue by imback82** [lemire/EWAHBoolArray#23]
Hi,
Can you expose read()/write() with raw pointers in addition to istream/ostream?

I am using boost::iostreams::stream<boost::iostreams::array_source> and std::stringstream but the overhead is pretty big (2x - 10x) compared to reading/writing with raw pointers.

Thanks!

**Comment by lemire** [comment]
Yes, good idea.

**Comment by imback82** [comment]
You are so quick. 👍 Can you also return the number of bytes read/written for the new APIs? Thanks!

**Comment by lemire** [comment]
Yes, we can indeed.

**Comment by lemire** [comment]
Fixed with release 0.6.0.

https://github.com/lemire/EWAHBoolArray/blob/master/headers/ewah.h#L471-L478

https://github.com/lemire/EWAHBoolArray/blob/master/headers/ewah.h#L440-L447

Should be safe and fast.

**Comment by lemire** [comment]
Tested with everything including Visual Studio...

https://ci.appveyor.com/project/lemire/EWAHBoolArray
