### ISSUE TITLE
What is the time complexity of bitset1 & bitset2 ?

### ISSUE THREAD

**Issue by zhzdeng** [lemire/EWAHBoolArray#25]
I want to know the time complexity of operator bitset1 & bitset2.
I know the complexity of std::set_intersection is up to linear in 2*(count1+count2)-1 (where countX is the distance between firstX and lastX): Compares and assigns elements.
The EWAHBoolArray can faster than  std::set_intersection ?
Thank.

**Comment by lemire** [comment]
You can't express it meaningfully using the same parameters as ``std::set_intersection``.

The running time complexity is specified in the documentation:

```
  /**
   * computes the logical and with another compressed bitmap
   * answer goes into container
   * Running time complexity is proportional to the sum of the compressed
   * bitmap sizes.
   *
   * The sizeInBits() of the result is equal to the maximum that of the current
   * bitmap's sizeInBits() and that of a.sizeInBits().
   */
  void logicaland(const EWAHBoolArray &a, EWAHBoolArray &container) const;
```

Reopen if this is not satisfactory, but I think it is a great answer.


For relevant benchmarks, please see:

* Daniel Lemire, Owen Kaser, Nathan Kurz, Luca Deri, Chris O’Hara, François Saint-Jacques, Gregory Ssi-Yan-Kai, [Roaring Bitmaps: Implementation of an Optimized Software Library](https://arxiv.org/abs/1709.07821), Software: Practice and Experience 48 (4), 2018
