### ISSUE TITLE
API to check if any bit is set?

### ISSUE THREAD

**Issue by imback82** [lemire/EWAHBoolArray#27]
What's the best (and fast) way to check if any bit is set in the bitmap?

**Comment by lemire** [comment]
This is part of the API...

```
  bool get(const size_t pos) const
```

If you call this repeatedly in a tight loop, it will be slow.

**Comment by imback82** [comment]
Maybe I wasn't clear enough.

auto ewah1 = EWAHBoolArray<>::bitmapOf(1, 2, 3, 4, 5);
auto ewah2 = EWAHBoolArray<>::bitmapOf(1, 2);

auto result = ewah1 & ewah2;

Now, I want to see if result has any bits set. One way I could do is call result.numberOfOnes() > 0 to check, but looks like the running complexity is not constant.

Can I achieve this in a constant time?

**Comment by lemire** [comment]
Ok. Update to the latest release and try ``empty()``. Reopen if it does not meet your need.
