### ISSUE TITLE
Move constructor/ move assignment operator

### ISSUE THREAD

**Issue by imback82** [lemire/EWAHBoolArray#28]
Can you add move constructor / move assignment operator so that EWAHBoolArray works better inside std::vector, etc.?

Please let me know if you want me to create a PR with the change.

**Comment by lemire** [comment]
PR invited!

**Comment by lemire** [comment]
Presumably, this has been resolved.

**Comment by Kraf11** [comment]
Que me eh perdido, ¿el que esta resuelto?

**Comment by lemire** [comment]
https://github.com/lemire/EWAHBoolArray/pull/29
