### ISSUE TITLE
Bitmap Sizing/Compression

### ISSUE THREAD

**Issue by cisaacson** [lemire/EWAHBoolArray#30]
We ran a test with 1000 and 10000 sequential long integers using 64-bit word size, and the array was 3.5MB in size for both. Should the RLE be able to compress this? Since the raw data is only 8K and 80K respectively I would have expected better compression.

In another test we used "roughly sequential" long integers (snowflake IDs), again with 1K and 10K values. This went to 188MB for both sets. Again the raw data is 8K and 80K in size.

Are there options to achieve better compression?

It may be that we should only use EWAHBoolArray for relatively sparse arrays, and when we have a lot of values like this we can try another structure, but we really like the capability of fast binary comparisons.

Any feedback appreciated.

**Comment by lemire** [comment]
Ok. So you have 1000 integer values in sorted order and after inserting the 1000 values into `EWAHBoolArray<uint64_t>` using the `set` method, then when you call ` sizeInBytes()` it returns a value equal to or larger than 3670016. 

If that's correct, please share these 1000 integer values.

**Comment by cisaacson** [comment]
Here is the sequential integer code snippet:

```cpp
uint64_t startNum = 123000000000000000;
  bitmap b2;
  for (uint64_t x = 0; x < 1000; ++x) {
    b2.set(startNum + x);
  }
  bitmap b3;

  for (uint64_t x = 0; x < 10000; ++x) {
    b3.set(startNum + x);
  }
```

For the snowflakeId values, they are very long numbers (18 decimal places), here are examples. For these we understand they won't compress well as they are non-sequential, any input on how to do it efficiently appreciated.

```
6473279675123630080
6473279675140407298
6473279675140407301
6473279675144601602
6473279675144601605
6473279675148795906
6473279675152990209
6473279675157184514
6473279675161378818
6473279675161378821
```

**Comment by lemire** [comment]
What happens in the first instance if you store the large 64-bit integer (123000000000000000) separately, and instead just do...

```C
  bitmap b2;
  for (uint64_t x = 0; x < 1000; ++x) {
    b2.set(x);
  }
  bitmap b3;

  for (uint64_t x = 0; x < 10000; ++x) {
    b3.set(x);
  }
```

?

One problem here is that your bitset has 123000000000000000 zero values. These do get compressed using RLE... but it is a very, very large number. It is kind of an adversarial case for EWAH to ask it to compress such a long sequence, it was not designed with such a scenario in mind.

If you can't or do not want to store offsets separately as I suggest, you might try with a 64-bit  ``Roaring``: https://github.com/RoaringBitmap/CRoaring/blob/master/cpp/roaring64map.hh

It should work ok. Learn more about Roaring: https://roaringbitmap.org

Pilosa uses 64-bit Roaring bitmaps: https://www.pilosa.com


(Heck, you might be able to use Pilosa!!!)

I am going to close this under the assumption that I have given you so useful indications.

You can keep asking away.

**Comment by janetmb** [comment]
Here's our test
```code
/**
 * This code is released under the
 * Apache License Version 2.0 http://www.apache.org/licenses/.
 *
 * (c) Daniel Lemire, http://lemire.me/en/
 */
#include <stdlib.h>
#include "ewah.h"
#include <iostream>
#include <fstream>

void testSnowflakeIds() {
  typedef EWAHBoolArray<uint64_t> bitmap;

  std::cout << "constructing bitmap with 1,000 entries" << std::endl;
  std::ifstream input("/Users/jmb/flakeids1000.txt");
  std::string tmp;
  uint64_t d;

  bitmap b2;
  uint64_t count = 0;
  while (!input.eof()) {
    std::getline(input, tmp);
    std::sscanf(tmp.c_str(), "%llu", &d);
    b2.set(d);
    // std::cout << "set value: " << d << std::endl;
    ++count;
  }
  std::cout << "set " << count << " entries in b2" << std::endl;
  input.close();

  std::cout << "constructing bitmap with 10000 entries" << std::endl;
  std::ifstream inputLg("/Users/jmb/flakeids10000.txt");

  bitmap b3;
  count = 0;
  while (!inputLg.eof()) {
    std::getline(inputLg, tmp);
    std::sscanf(tmp.c_str(), "%llu", &d);
    b3.set(d);
    // std::cout << "set value: " << d << std::endl;
    ++count;
  }
  std::cout << "set " << count << " entries in b3" << std::endl;
  inputLg.close();

  std::cout << "memory usage of bitmap with 1000 snowflakeids = " << b2.sizeInBytes()
      << " bytes" << std::endl;
  std::cout << "memory usage of bitmap with 10000 snowflakeids = "
      << b3.sizeInBytes() << " bytes" << std::endl;

}

void testLargeNumbers() {
  typedef EWAHBoolArray<uint64_t> bitmap;
  uint64_t startNum = 12300000000000;

  std::cout << "constructing bitmap with 1,000 entries" << std::endl;
  bitmap b2;
  for (uint64_t x = 0; x < 1000; ++x) {
    b2.set(startNum + x);
  }
  std::cout << "constructing bitmap with 10,000 entries" << std::endl;

  bitmap b3;

  for (uint64_t x = 0; x < 10000; ++x) {
    b3.set(startNum + x);
  }
  std::cout << "memory usage of bitmap with 1000 entries = " << b2.sizeInBytes()
      << " bytes" << std::endl;
  std::cout << "memory usage of bitmap with 10000 entries = "
      << b3.sizeInBytes() << " bytes" << std::endl;


}
int main(void) {

  std::cout << "==== testSnowflakeIds === " << std::endl;
  testSnowflakeIds();

  std::cout << "==== testLargeNumbers === " << std::endl;
  testLargeNumbers();

  return EXIT_SUCCESS;
}
```


When I run this here is the output:
```==== testSnowflakeIds === 
constructing bitmap with 1,000 entries
set 1001 entries in b2
constructing bitmap with 10000 entries
set 10001 entries in b3
memory usage of bitmap with 1000 snowflakeids = 188400448 bytes
memory usage of bitmap with 10000 snowflakeids = 188403040 bytes
==== testLargeNumbers === 
constructing bitmap with 1,000 entries
constructing bitmap with 10,000 entries
memory usage of bitmap with 1000 entries = 376 bytes
memory usage of bitmap with 10000 entries = 376 bytes
```
