### ISSUE TITLE
&= and |= operators

### ISSUE THREAD

**Issue by kiarashgl** [lemire/EWAHBoolArray#31]
Hi
I want to &= and |= a bitset with some bitsets. In order to that, I have to make the bitset equal to the logical and (logical or) result; for example:
`original_bitset = original_bitset.logicaland(other_bitset);`
Does this API give us another efficient way to get this result, without having the cost of assignment operator?

**Comment by lemire** [comment]
For EWAHBoolArray, the proper way is just as you describe`original_bitset = original_bitset.logicaland(other_bitset);`.

> Does this API give us another efficient way to get this result, without having the cost of assignment operator?

It does not. 

If you can design a more efficient approach, please consider doing a pull request.
