### ISSUE TITLE
Build fails in 32 bit mode on MSVC

### ISSUE THREAD

**Issue by zarianw** [lemire/EWAHBoolArray#6]
The 32 bit build fails with the following errors:

Error	1	error C3861: '_BitScanForward64': identifier not found	e:\code\forks\ewahboolarray\headers\ewahutil.h	49	1	EWAHBoolArrayTest
Error	2	error C3861: '__popcnt64': identifier not found	e:\code\forks\ewahboolarray\headers\ewahutil.h	197	1	EWAHBoolArrayTest

The code needs to use _BitScanForward and __popcnt in 32 bit build. I tried changing that by adding the compile time switch (using #if _WIN64), the build was fine but then a whole bunch of unit tests were failing in 32 bit build.

The failing tests were originating from
if (!testNanJiang<uint64_t>())

I don't know if these can be ignored for the 32 bit build because they are testing uint64_t.

**Comment by lemire** [comment]
Closing this issue.
