### ISSUE TITLE
intersects method returns incorrect value

### ISSUE THREAD

**Issue by mkachmar** [lemire/EWAHBoolArray#8]
Hi Daniel,
It seems from my tests (attached in the email I sent you) that the intersects method may return an incorrect value. I am just noting this here as an issue in case someone else runs into it.

Thank you for your help with this.
Mazen

**Comment by mkachmar** [comment]
The latest fix that Daniel provided solved this issue. Thanks Daniel!

**Comment by lemire** [comment]
@mkachmar 

If you have time, we could do with a few more unit tests...
